version: 2

updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: daily
    versioning-strategy: increase
    labels:
      - npm
      - dependencies
  - package-ecosystem: npm
    directory: /example
    open-pull-requests-limit: 2
    schedule:
      interval: daily
    versioning-strategy: increase
    labels:
      - npm
      - dependencies
